services:
    database:
        container_name: database
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=waterlevel
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 10
            start_period: 3s
        # volumes:
        #     - database-data:/var/lib/postgresql/data
    backend:
        container_name: backend
        # depends_on:
        #     database:
        #         condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:80:8000
        env_file:
            - src/.env
        healthcheck:
            test: curl -X GET --fail http://0.0.0.0:8000/api/v1 -Is
            interval: 20s
            timeout: 5s
            retries: 10
            start_period: 5s
# volumes:
#     database-data: {}