services:
    database:
        container_name: database
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        # volumes:
        #     - database-data:/var/lib/postgresql/data
    backend:
        container_name: backend
        depends_on: [database]
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 3001
        env_file:
            - src/.env
# volumes:
#     database-data: {}