[default]
address = "0.0.0.0"
port = 8000
secret_key = "5Fj6QreenJIVftTw6qXwInx2qUNI8EQPJfNbHzxxnGY="
limits = { form = "64 kB", json = "1 MiB" }

[debug]
# address = "localhost"
limits = { json = "10MiB" }

[release]
port = 8000
limits = { forms = 32768 }